# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "16.3.0"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependecies
        run: yarn install
        env:
          CI: true

      - name: Build
        run: yarn build 

      - name: Run Eslint
        run: yarn lint

      - name: Run Unit Test
        run: yarn test
